using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		public partial class TBL_Item : BGEntity
		{

			//=============================================================
			//||                   Generated by BansheeGz Code Generator ||
			//=============================================================

			public class Factory : BGEntity.EntityFactory
			{
				public BGEntity NewEntity(BGMetaEntity meta)
				{
					return new TBL_Item(meta);
				}
				public BGEntity NewEntity(BGMetaEntity meta, BGId id)
				{
					return new TBL_Item(meta, id);
				}
			}
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4767826775003001759,13439111249775766426));
					return _metaDefault;
				}
			}
			public static BansheeGz.BGDatabase.BGRepoEvents Events
			{
				get
				{
					return BGRepo.I.Events;
				}
			}
			private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
			public static int CountEntities
			{
				get
				{
					return MetaDefault.CountEntities;
				}
			}
			public System.String name
			{
				get
				{
					return _name[Index];
				}
				set
				{
					_name[Index] = value;
				}
			}
			public System.String Description
			{
				get
				{
					return _Description[Index];
				}
				set
				{
					_Description[Index] = value;
				}
			}
			public UnityEngine.Sprite Icon
			{
				get
				{
					return _Icon[Index];
				}
			}
			public ItemType ItemType
			{
				get
				{
					return (ItemType) _ItemType[Index];
				}
				set
				{
					_ItemType[Index] = value;
				}
			}
			public CropType CropType
			{
				get
				{
					return (CropType) _CropType[Index];
				}
				set
				{
					_CropType[Index] = value;
				}
			}
			public System.Int32 SellingPrice
			{
				get
				{
					return _SellingPrice[Index];
				}
				set
				{
					_SellingPrice[Index] = value;
				}
			}
			public System.Int32 PurchasePrice
			{
				get
				{
					return _PurchasePrice[Index];
				}
				set
				{
					_PurchasePrice[Index] = value;
				}
			}
			public System.Int32 GrowTime
			{
				get
				{
					return _GrowTime[Index];
				}
				set
				{
					_GrowTime[Index] = value;
				}
			}
			public System.Int32 MinDropCount
			{
				get
				{
					return _MinDropCount[Index];
				}
				set
				{
					_MinDropCount[Index] = value;
				}
			}
			public System.Int32 MaxDropCount
			{
				get
				{
					return _MaxDropCount[Index];
				}
				set
				{
					_MaxDropCount[Index] = value;
				}
			}
			public System.Int32 MinInventoryCount
			{
				get
				{
					return _MinInventoryCount[Index];
				}
				set
				{
					_MinInventoryCount[Index] = value;
				}
			}
			public System.Int32 MaxInventoryCount
			{
				get
				{
					return _MaxInventoryCount[Index];
				}
				set
				{
					_MaxInventoryCount[Index] = value;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5041415605477812183,13068105493378511773));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Description;
			public static BansheeGz.BGDatabase.BGFieldString _Description
			{
				get
				{
					if(_ufle12jhs77_Description==null || _ufle12jhs77_Description.IsDeleted) _ufle12jhs77_Description=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5121955587311381659,17219275046198090646));
					return _ufle12jhs77_Description;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_Icon;
			public static BansheeGz.BGDatabase.BGFieldUnitySprite _Icon
			{
				get
				{
					if(_ufle12jhs77_Icon==null || _ufle12jhs77_Icon.IsDeleted) _ufle12jhs77_Icon=(BansheeGz.BGDatabase.BGFieldUnitySprite) MetaDefault.GetField(new BGId(4669056986025007716,14889490884379400878));
					return _ufle12jhs77_Icon;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_ItemType;
			public static BansheeGz.BGDatabase.BGFieldEnum _ItemType
			{
				get
				{
					if(_ufle12jhs77_ItemType==null || _ufle12jhs77_ItemType.IsDeleted) _ufle12jhs77_ItemType=(BansheeGz.BGDatabase.BGFieldEnum) MetaDefault.GetField(new BGId(5307786620036269905,5365769654642340009));
					return _ufle12jhs77_ItemType;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_CropType;
			public static BansheeGz.BGDatabase.BGFieldEnum _CropType
			{
				get
				{
					if(_ufle12jhs77_CropType==null || _ufle12jhs77_CropType.IsDeleted) _ufle12jhs77_CropType=(BansheeGz.BGDatabase.BGFieldEnum) MetaDefault.GetField(new BGId(5269372244093188146,8233091732930171300));
					return _ufle12jhs77_CropType;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_SellingPrice;
			public static BansheeGz.BGDatabase.BGFieldInt _SellingPrice
			{
				get
				{
					if(_ufle12jhs77_SellingPrice==null || _ufle12jhs77_SellingPrice.IsDeleted) _ufle12jhs77_SellingPrice=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5125575041386818564,17459570795109511614));
					return _ufle12jhs77_SellingPrice;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_PurchasePrice;
			public static BansheeGz.BGDatabase.BGFieldInt _PurchasePrice
			{
				get
				{
					if(_ufle12jhs77_PurchasePrice==null || _ufle12jhs77_PurchasePrice.IsDeleted) _ufle12jhs77_PurchasePrice=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5596543304846418720,17008170582645990016));
					return _ufle12jhs77_PurchasePrice;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_GrowTime;
			public static BansheeGz.BGDatabase.BGFieldInt _GrowTime
			{
				get
				{
					if(_ufle12jhs77_GrowTime==null || _ufle12jhs77_GrowTime.IsDeleted) _ufle12jhs77_GrowTime=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5048951192243860347,9169207098239889847));
					return _ufle12jhs77_GrowTime;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MinDropCount;
			public static BansheeGz.BGDatabase.BGFieldInt _MinDropCount
			{
				get
				{
					if(_ufle12jhs77_MinDropCount==null || _ufle12jhs77_MinDropCount.IsDeleted) _ufle12jhs77_MinDropCount=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5545591621229992228,760196633426810525));
					return _ufle12jhs77_MinDropCount;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MaxDropCount;
			public static BansheeGz.BGDatabase.BGFieldInt _MaxDropCount
			{
				get
				{
					if(_ufle12jhs77_MaxDropCount==null || _ufle12jhs77_MaxDropCount.IsDeleted) _ufle12jhs77_MaxDropCount=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5625237563363088061,11476912943658055871));
					return _ufle12jhs77_MaxDropCount;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MinInventoryCount;
			public static BansheeGz.BGDatabase.BGFieldInt _MinInventoryCount
			{
				get
				{
					if(_ufle12jhs77_MinInventoryCount==null || _ufle12jhs77_MinInventoryCount.IsDeleted) _ufle12jhs77_MinInventoryCount=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4748712727651878417,13743980054511813049));
					return _ufle12jhs77_MinInventoryCount;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MaxInventoryCount;
			public static BansheeGz.BGDatabase.BGFieldInt _MaxInventoryCount
			{
				get
				{
					if(_ufle12jhs77_MaxInventoryCount==null || _ufle12jhs77_MaxInventoryCount.IsDeleted) _ufle12jhs77_MaxInventoryCount=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5686710475950314285,10464852819127195578));
					return _ufle12jhs77_MaxInventoryCount;
				}
			}
			private static readonly TBL_Item.Factory _factory0_PFS = new TBL_Item.Factory();
			public TBL_Item() : base(MetaDefault)
			{
			}
			public TBL_Item(BGId id) : base(MetaDefault, id)
			{
			}
			public TBL_Item(BGMetaEntity meta) : base(meta)
			{
			}
			public TBL_Item(BGMetaEntity meta, BGId id) : base(meta, id)
			{
			}
			public static TBL_Item FindEntity(Predicate<TBL_Item> filter)
			{
				return MetaDefault.FindEntity(entity => filter==null || filter((TBL_Item) entity)) as TBL_Item;
			}
			public static List<TBL_Item> FindEntities(Predicate<TBL_Item> filter, List<TBL_Item> result=null, Comparison<TBL_Item> sort=null)
			{
				result = result ?? new List<TBL_Item>();
				_find_Entities_Result.Clear();
				MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((TBL_Item) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((TBL_Item) e1, (TBL_Item) e2));
				if (_find_Entities_Result.Count != 0)
				{
					for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((TBL_Item) _find_Entities_Result[i]);
					_find_Entities_Result.Clear();
				}
				return result;
			}
			public static void ForEachEntity(Action<TBL_Item> action, Predicate<TBL_Item> filter=null, Comparison<TBL_Item> sort=null)
			{
				MetaDefault.ForEachEntity(entity => action((TBL_Item) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((TBL_Item) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((TBL_Item)e1,(TBL_Item)e2));
			}
			public static TBL_Item GetEntity(BGId entityId)
			{
				return (TBL_Item) MetaDefault.GetEntity(entityId);
			}
			public static TBL_Item GetEntity(int index)
			{
				return (TBL_Item) MetaDefault[index];
			}
			public static TBL_Item GetEntity(string entityName)
			{
				return (TBL_Item) MetaDefault.GetEntity(entityName);
			}
			public static TBL_Item NewEntity()
			{
				return (TBL_Item) MetaDefault.NewEntity();
			}
		}

#pragma warning restore 414
